const IMAGES = {
  image1: new URL("./pp.jpg", import.meta.url).href,
  image2: new URL("./pix_1.png", import.meta.url).href,
  image3: new URL("./p2.jpg", import.meta.url).href,
  home: new URL("./home.png", import.meta.url).href,
  github: new URL("./github.svg", import.meta.url).href,
  instagram: new URL("./instagram.svg", import.meta.url).href,
  email: new URL("./envelope.svg", import.meta.url).href,
  linkedin: new URL("./linkedin.svg", import.meta.url).href,
  telegram: new URL("./telegram.svg", import.meta.url).href,
  frontend: new URL("./frontend--.png", import.meta.url).href,
  html: new URL("./html-5.svg", import.meta.url).href,
  css: new URL("./css3.svg", import.meta.url).href,
  react: new URL("./react.svg", import.meta.url).href,
  js: new URL("./javascript.svg", import.meta.url).href,
  git: new URL("./git.svg", import.meta.url).href,
  sass: new URL("./sass.svg", import.meta.url).href,
  vite: new URL("./vite.svg", import.meta.url).href,
  code: new URL("./code.svg", import.meta.url).href,
  maintenance: new URL("./maintenance.svg", import.meta.url).href,
  tailwind: new URL("./tailwind.svg", import.meta.url).href,
  github1: new URL("./github-1.svg", import.meta.url).href,
  back: new URL("./back-to-top.svg", import.meta.url).href,
  portfolio: new URL("./portfolioSnnip.PNG", import.meta.url).href,
  weatherIt: new URL("./weatherIt.PNG", import.meta.url).href,
  abyssinia: new URL("./abyssinia.png", import.meta.url).href,
  call: new URL("./call.svg", import.meta.url).href,
  location: new URL("./location.svg", import.meta.url).href,
  pix2: new URL("./pix_2.png", import.meta.url).href,
  projects: new URL("./project.png", import.meta.url).href,
  pix3: new URL("./pix_3.png", import.meta.url).href,
};

export default IMAGES;
